CREATE TABLE IF NOT EXISTS matches (
  id SERIAL PRIMARY KEY,
  home_team TEXT NOT NULL,
  away_team TEXT NOT NULL,
  venue TEXT,
  match_date DATE,
  match_time TEXT,
  tournament TEXT,
  first_half_seconds INTEGER NOT NULL DEFAULT 0,
  second_half_seconds INTEGER NOT NULL DEFAULT 0,
  first_half_ended BOOLEAN NOT NULL DEFAULT FALSE,
  saved_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS actions (
  id SERIAL PRIMARY KEY,
  match_id INTEGER NOT NULL REFERENCES matches(id) ON DELETE CASCADE,
  half TEXT NOT NULL,
  time INTEGER NOT NULL,
  team TEXT NOT NULL,
  action_label TEXT NOT NULL,
  detail TEXT,
  coord TEXT,
  sp BOOLEAN NOT NULL DEFAULT FALSE,
  goal BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

ALTER TABLE actions ADD COLUMN IF NOT EXISTS sp BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE actions ADD COLUMN IF NOT EXISTS goal BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE matches ADD COLUMN IF NOT EXISTS first_half_seconds INTEGER NOT NULL DEFAULT 0;
ALTER TABLE matches ADD COLUMN IF NOT EXISTS second_half_seconds INTEGER NOT NULL DEFAULT 0;
ALTER TABLE matches ADD COLUMN IF NOT EXISTS first_half_ended BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE matches ADD COLUMN IF NOT EXISTS saved_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW();
ALTER TABLE matches ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW();
ALTER TABLE actions ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW();

DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_name = 'actions'
      AND column_name = 'time'
      AND data_type <> 'integer'
  ) THEN
    ALTER TABLE actions
    ALTER COLUMN time TYPE INTEGER
    USING CASE
      WHEN time ~ '^[0-9]+$' THEN time::INTEGER
      WHEN time ~ '^[0-9]+:[0-5][0-9]$' THEN split_part(time, ':', 1)::INTEGER * 60 + split_part(time, ':', 2)::INTEGER
      ELSE 0
    END;
  END IF;
END $$;
