CREATE TABLE IF NOT EXISTS matches (
  id SERIAL PRIMARY KEY,
  home_team TEXT NOT NULL,
  away_team TEXT NOT NULL,
  venue TEXT,
  match_date DATE,
  match_time TEXT,
  tournament TEXT,
  first_half_seconds INTEGER NOT NULL DEFAULT 0,
  second_half_seconds INTEGER NOT NULL DEFAULT 0,
  first_half_ended BOOLEAN NOT NULL DEFAULT FALSE,
  saved_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS actions (
  id SERIAL PRIMARY KEY,
  match_id INTEGER NOT NULL REFERENCES matches(id) ON DELETE CASCADE,
  half TEXT NOT NULL,
  time TEXT NOT NULL,
  team TEXT NOT NULL,
  action_label TEXT NOT NULL,
  detail TEXT,
  coord TEXT,
  sp BOOLEAN NOT NULL DEFAULT FALSE,
  goal BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

ALTER TABLE actions ADD COLUMN IF NOT EXISTS sp BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE actions ADD COLUMN IF NOT EXISTS goal BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE matches ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW();
ALTER TABLE actions ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW();
